version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: shellai
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "shellai_{{.Os}}_{{.Arch}}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: SachinVenugopalan30
    name: shellai
  draft: false
  prerelease: auto
