package cmd

import (
	"fmt"

	"github.com/spf13/cobra"

	"github.com/SachinVenugopalan30/shell-ai/internal/history"
)

var historyLimit int

var historyCmd = &cobra.Command{
	Use:   "history",
	Short: "Show recent commands generated by shellai",
	Args:  cobra.NoArgs,
	RunE: func(_ *cobra.Command, _ []string) error {
		entries, err := history.Load(history.DefaultPath(), historyLimit)
		if err != nil {
			return err
		}
		if len(entries) == 0 {
			fmt.Println("No history yet.")
			return nil
		}
		for i, e := range entries {
			status := "✓ executed"
			if !e.Executed {
				status = "✗ aborted"
			}
			fmt.Printf("#%d  %s\n", i+1, e.Timestamp.Local().Format("2006-01-02 15:04"))
			fmt.Printf("    Intent:  %s\n", e.Intent)
			fmt.Printf("    Command: %s\n", e.Command)
			fmt.Printf("    Status:  %s\n\n", status)
		}
		return nil
	},
}

func init() {
	historyCmd.Flags().IntVarP(&historyLimit, "limit", "n", 20, "Max number of entries to show")
	Root.AddCommand(historyCmd)
}
